== Notes on how it works
This project takes inspiration from a https://blog.jread.com/auto-build-and-host-pretty-html-documentation-using-asciidoc-github-pages-github-actions-758a03f93d7d[blogpost by James Read]. Read this post if you want to add CSS styling or deploy on your own domain name.

The workflow contains two steps as shown below.

image::workflow.dio.svg[]

=== Notes on Asciidoctor

==== Single Page Output
This approach generates a single HTML file. If you want to generate a separate file per section, then look into these options:

- https://github.com/owenh000/asciidoctor-multipage[Asciidoctor multipage plugin]
- https://antora.org/[Antora]

==== Managing Images
Your Asciidoc source may reference images, as shown in the example above. Asciidoctor does not copy images from the source directory to the target directory. There are several solutions here:

. Embed the images in the HTML file using the https://docs.asciidoctor.org/asciidoctor/latest/html-backend/manage-images/[data-uri attribute]. This is the approach used here.
. Put the images _and_ the Asciidoc sources in the /docs directory. The publish step will copy the directory contents across to gh-pages. A slight drawback of this method: it will also copy the Asciidoc sources.
. Use Antora.

=== Notes on the GitHub Pages action
See documentation at https://github.com/peaceiris/actions-gh-pages


