== Steps
=== Create a new repository on GitHub
. Login to GitHub, click on New and give the repository a name.
. Add a README. Although we'll be renaming this file later, the repo needs at least one file in order to have a default branch.
. Click Create Repository
. As we will be using , we need to configure access. Under Settings > Actions > General > Workflow permissions, select *Read and write permissions* and press [Save].

=== Clone to local repository
. After the repository is created, click on the green Code button and click Local > HTTPS to copy the URL.
. Navigate to the folder in which you want to create a new folder with the repository.
. Clone the repository using the URL previously copied:
+
----
git clone https://github.com/username/project.git
----

=== Create folder/file structure
. cd into the git repo
+
----
cd project
----
. Rename the README and create folders using the following commands:
+
----
git mv README.md README.adoc
mkdir src
mkdir src\docs
mkdir .github
mkdir .github\workflows
----
. Edit `README.adoc`
. Create `src/docs/index.adoc` +
  You can use the file in this repo as an example
. Create file `.github/workflows/build-asciidoc.yml` as 
+
----
include::../../.github/workflows/build-asciidoc.yml[]
----
. Add these new files to the repository:
+
----
git add .
----
. Commit and push the files:
+
----
git commit -m "Initial Structure"
git push -u origin main
----

. On GitHub.com, navigate to the Actions tab. You will probably see a failed run of the of the workflow. See instructions on https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token


=== Configure GitHub Pages

The Asciidoc source has been rendered to HTML in branch `gh-pages`.

. Navigate to Settings > Pages.
. Set the source to gh-pages (root) and save.
. At the top you will see the site URL. Copy it.
. Click on the code tab
. On the right hand side (About), click on the Settings icon.
. Set the website field to *Use your GitHub Pages website* and press Save.

