== Steps
=== Create a new repository on GitHub
. Login to GitHub, click on New and give the repository a name.
. Add a README. Although we'll be renaming this file later, the repo needs at least one file in order to have a default branch.
. Click Create Repository
.. After the repository is created, click on the green Code button and click on the disk icon to copy the URL.

=== Clone to local repository
. Navigate to the folder in which you want to create a new folder with the repository.
. Clone the repository using the URL previously copied:
+
----
git clone https://github.com/username/project.git
----

=== Create folder/file structure
. cd into the git repo
+
----
cd project
----
. Rename the README and create folders using the following commands:
+
----
git mv README.md README.adoc
mkdir src
mkdir src\docs
mkdir .github
mkdir .github\workflows
----
. Edit `README.adoc`
. Create `src/docs/index.adoc` +
  You can use the file in this repo as an example
. Create file `.github/workflows/build-asciidoc.yml` as 
+
----
include::../../.github/workflows/build-asciidoc.yml[]
----
. Add these new files to the repository:
+
----
git add .
----
. Commit and push the files:
+
----
git commit -m "Initial Structure"
git push -u origin main
----

=== Configure GitHub Pages
. On GitHub.com, navigate to the Actions tab. You will hopefully see a successful run of the workflow. The Asciidoc source has been rendered to HTML in branch `gh-pages`.
. Navigate to Settings > Pages.
. Set the source to gh-pages (root) and save.
. At the top you will see the site URL. Copy it.
. Click on the code tab
. On the right hand side (About), click on the Settings icon.
. Paste the URL in the website field and press Save.

